### ISSUE TITLE
v0.1.2 The transformation has been interrupted by an CLI error.

### ISSUE THREAD

**Issue by haotian0430** [private-dreamnet/dreamtime#52]
Error: The transformation has been interrupted by an CLI error.
This can be caused by:
-A corrupt installation (commonly: The checkpoints folder was not found in cli/)
-Incompatible system
-If you are using GPU: The NVIDIA graphics card could not be found -If you are using CPU: Insufficient RAM.Buy more RAM!
The CLI has reported the following error, take a screenshot to get more information:
[18476] Failed to execute script main Traceback (most recent call last):
File "main.py", line 101, in <module>
File "main.py", line 74, in main File "run.py", line 167, in process
File nopencv_transform\dress_to_correct.py", line 12, in create_correct File "opencv_transform\dress_to_correct.py"f line 19, in correct_color AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by haotian0430** [comment]
Gpu and cpu are both wrong

**Comment by deeppppp** [comment]
can you confirm you place the 'checkpoints' folder with the 
cm.lib
mm.lib
mn.lib
files
into the folder called 'cli' inside the folder you installed DreamTime in?

**Comment by kolessios** [comment]
The error message indicates that DreamPower could not load the cropped photo, this may occur when the location where the cropped photos are stored has special characters (accents, spaces, etc.), please check `Settings -> Folders -> Cropped Folder`.

**Comment by haotian0430** [comment]
> 你能否确认你将带有
> cm.lib 
> mm.lib 
> mn.lib 
> 文件的'checkpoints'文件夹
> 放入你安装DreamTime的文件夹中名为'cli'的文件夹中？

yes

**Comment by haotian0430** [comment]
> 错误消息表明DreamPower无法加载裁剪的照片，当存储裁剪的照片的位置有特殊字符（重音符，空格等）时，可能会出现这种情况，请检查`Settings -> Folders -> Cropped Folder`。

This is version 0.1.2. It seems that there are no configurations that you said.

**Comment by deeppppp** [comment]
A new version has been released, v1.0.0 it has bug fixes for the issue with special characters in the image name (path). You can upgrade to that version to fix the issue.
Or if you want to keep working with v0.1.2 you can place the input file on the c:\ root folder and rename the input file to 'abc.jpg' or 'abc.png' depending on the current file extension.
